---
version: 0.0.1
slug: speech-to-phrase
name: speech-to-phrase
description: Fast but limited speech-to-text
url: http://github.com/OHF-voice/speech-to-phrase
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
map:
  - share:rw
backup_exclude:
  - "*/models/*"
ingress: true
homeassistant_api: true
options:
  debug_logging: false
schema:
  debug_logging: bool
ports:
  "10300/tcp": null
homeassistant: 2023.11.0
